export const nodoPerfiles = 'localhost'
export const puertoPerfiles = '5002'
export const allProfiles = 'profiles'
export const postProfile = 'profiles'
export const editProfile = 'edit/profile'
export const editPassword = 'edit/password'
export const activeProfile = 'active/profiles'
